### ISSUE TITLE
neutron-lib should point to review.rdoproject, not openstack-packages

### ISSUE THREAD

**Issue by dmsimard** [redhat-openstack/rdoinfo#170]
See: https://github.com/redhat-openstack/rdoinfo/blob/d3262f10f15c3286be90d1f4a54f4f99af6c91d3/rdo.yml#L393

**Comment by dmsimard** [comment]
ping @apevec @javierpena

**Comment by yazug** [comment]
this one was showing up in current_passed_ci versions.csv as the only one pulling from openstack-packages yet

**Comment by apevec** [comment]
I guess this was mis-merged in the new rdoinfo for rpmfactory,
project itself was migrated correctly:
https://github.com/rdo-packages/neutron-lib-distgit/commits/rpm-master

**Comment by apevec** [comment]
http://review.rdoproject.org/r/1138
